i add ex. 9-12
jakubsbl/python_learning pull request #5
Opened 2022-09-07 11:22 UTC by jakubsbl

2022-09-12 22:00 UTC, rmikl requested changes
python 10 -robisz potege

2022-09-13 21:33 UTC, jakubsbl commented
done.

2022-09-14 20:33 UTC, rmikl requested changes
in excercise 10 the result should be:  2 + 22+ 222  = 246 
in Your case it is 2+ 4 + 6 = 12
change how you creating "n2" and "n3" 
correct example: n2 = 2 + (2*10) = 22
the same for n3

2022-09-16 18:40 UTC, rmikl approved these changes

2022-09-20 18:32 UTC, merged